#!/usr/bin/env bash
# EgoSim chunkwise Stage 3 Object-DMD.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/egosim_train_common.sh"

CONFIG_PATH="${CONFIG_PATH:-${ROOT_DIR}/configs/causal_forcing_dmd_chunkwise_egosim_object_dmd.yaml}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
CUSTOM_PREFIX="${CUSTOM_PREFIX:-}"
CUSTOM_SUFFIX="${CUSTOM_SUFFIX:-}"
RUN_PREFIX="${CUSTOM_PREFIX:+${CUSTOM_PREFIX}-}"
RUN_SUFFIX="${CUSTOM_SUFFIX:+-${CUSTOM_SUFFIX}}"
RUN_NAME="${RUN_NAME:-${RUN_PREFIX}${RUN_TIMESTAMP}${RUN_SUFFIX}}"
LOGDIR="${LOGDIR:-${ROOT_DIR}/checkpoints/egosim_stage3_dmd_chunkwise_object_dmd/${RUN_NAME}}"
RUN_OUTPUT_DIR="${RUN_OUTPUT_DIR:-${ROOT_DIR}/output/egosim_stage3_dmd_chunkwise_object_dmd_${RUN_NAME}}"
EGOSIM_MODEL_ROOT="${EGOSIM_MODEL_ROOT:-${WORK_ROOT}/model/EgoSim-14B}"
EGOSIM_DATA_PATH="${EGOSIM_DATA_PATH:-${USER_ROOT}/datasets/luyitas/egosim_egodex_egovid/cache/train/egodex}"
STAGE2_CKPT="${STAGE2_CKPT:-${ROOT_DIR}/checkpoints/egosim_stage2_cd_chunkwise/checkpoint_model_001000/model.pt}"
REAL_SCORE_CKPT="${REAL_SCORE_CKPT:-${EGOSIM_MODEL_ROOT}/diffusion_pytorch_model.safetensors}"
FAKE_SCORE_CKPT="${FAKE_SCORE_CKPT:-${EGOSIM_MODEL_ROOT}/diffusion_pytorch_model.safetensors}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-600}"
SAVE_EVAL_INTERVAL="${SAVE_EVAL_INTERVAL:-200}"
GUIDANCE_SCALE="${GUIDANCE_SCALE:-3.0}"
PHYSICS_TRACK_MODE="${PHYSICS_TRACK_MODE:-new}"
OBJECT_DMD_WEIGHT="${OBJECT_DMD_WEIGHT:-1.0}"
BACKGROUND_DMD_WEIGHT="${BACKGROUND_DMD_WEIGHT:-0.1}"
MASTER_PORT="${MASTER_PORT:-6064}"
RDZV_ID="${RDZV_ID:-${MA_JOB_NAME:-egosim_stage3_dmd_chunkwise_object_dmd}}"

egosim_require   "${PYTHON_BIN}" "${CONFIG_PATH}" "${EGOSIM_DATA_PATH}"   "${STAGE2_CKPT}" "${REAL_SCORE_CKPT}" "${FAKE_SCORE_CKPT}"
egosim_prepare_distributed

mkdir -p "${RUN_OUTPUT_DIR}/runtime_configs" "${RUN_OUTPUT_DIR}/wandb" "${LOGDIR}"
RUNTIME_CONFIG="${RUN_OUTPUT_DIR}/runtime_configs/egosim_stage3_chunkwise_object_dmd_node${NODE_RANK}.yaml"
cp "${CONFIG_PATH}" "${RUNTIME_CONFIG}"
egosim_set_yaml data_path "${EGOSIM_DATA_PATH}" "${RUNTIME_CONFIG}"
egosim_set_yaml egosim_model_root "${EGOSIM_MODEL_ROOT}" "${RUNTIME_CONFIG}"
egosim_set_yaml generator_ckpt "${STAGE2_CKPT}" "${RUNTIME_CONFIG}"
egosim_set_yaml real_score_ckpt "${REAL_SCORE_CKPT}" "${RUNTIME_CONFIG}"
egosim_set_yaml fake_score_ckpt "${FAKE_SCORE_CKPT}" "${RUNTIME_CONFIG}"
egosim_set_yaml max_train_steps "${MAX_TRAIN_STEPS}" "${RUNTIME_CONFIG}"
egosim_set_yaml log_iters "${SAVE_EVAL_INTERVAL}" "${RUNTIME_CONFIG}"
egosim_set_yaml guidance_scale "${GUIDANCE_SCALE}" "${RUNTIME_CONFIG}"
egosim_set_yaml physics_track_mode "${PHYSICS_TRACK_MODE}" "${RUNTIME_CONFIG}"
egosim_set_yaml object_dmd_weight "${OBJECT_DMD_WEIGHT}" "${RUNTIME_CONFIG}"
egosim_set_yaml background_dmd_weight "${BACKGROUND_DMD_WEIGHT}" "${RUNTIME_CONFIG}"

LOG_FILE="${LOG_FILE:-${RUN_OUTPUT_DIR}/egosim_stage3_chunkwise_object_dmd_node${NODE_RANK}_${RUN_TIMESTAMP}.log}"
{
  echo "===== EgoSim Stage-3 Causal Forcing++ Chunkwise Object-DMD ====="
  echo "RUN_NAME=${RUN_NAME}"
  echo "CUSTOM_PREFIX=${CUSTOM_PREFIX}"
  echo "CUSTOM_SUFFIX=${CUSTOM_SUFFIX}"
  echo "LOGDIR=${LOGDIR}"
  echo "RUN_OUTPUT_DIR=${RUN_OUTPUT_DIR}"
  echo "CONFIG_PATH=${RUNTIME_CONFIG}"
  echo "STAGE2_CKPT=${STAGE2_CKPT}"
  echo "REAL_SCORE_CKPT=${REAL_SCORE_CKPT}"
  echo "FAKE_SCORE_CKPT=${FAKE_SCORE_CKPT}"
  echo "MAX_TRAIN_STEPS=${MAX_TRAIN_STEPS}, SAVE_EVAL_INTERVAL=${SAVE_EVAL_INTERVAL}"
  echo "GUIDANCE_SCALE=$(awk '/^guidance_scale:/ {print $2; exit}' "${RUNTIME_CONFIG}")"
  echo "PHYSICS_TRACK_MODE=$(awk '/^physics_track_mode:/ {print $2; exit}' "${RUNTIME_CONFIG}")"
  echo "OBJECT_DMD_WEIGHT=$(awk '/^object_dmd_weight:/ {print $2; exit}' "${RUNTIME_CONFIG}")"
  echo "BACKGROUND_DMD_WEIGHT=$(awk '/^background_dmd_weight:/ {print $2; exit}' "${RUNTIME_CONFIG}")"
  echo "WANDB_PROJECT=$(awk '/^wandb_project:/ {print $2; exit}' "${RUNTIME_CONFIG}")"
  echo "NNODES=${NNODES}, NPROC_PER_NODE=${NPROC_PER_NODE}"
} | tee "${LOG_FILE}"
egosim_train "${LOG_FILE}" "${RUNTIME_CONFIG}" "${LOGDIR}" "${RUN_OUTPUT_DIR}" "$@"
